# Generated by Django 6.0.6 on 2026-06-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0003_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(default='Open', max_length=20),
        ),
    ]
